name: macler
channels:
  - defaults
dependencies:
  - numpy=1.18.1
  - numpy-base=1.18.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - scipy=1.5.2
  - sympy=1.6.2
  - pandas=1.2
  - python=3.7 # some libs lack support for latter versions
  - ipython=7.20 # a powerful Python shell
  - jupyter=1.0 # to edit and run Jupyter notebooks
  - numexpr=2.7 # used only in the Pandas tutorial for numerical expressions
  - opencv=4.5 # used only in chapter 18 by TF Agents for image preprocessing
  - pillow=8.1 # image manipulation library, (used by matplotlib.image.imread)
  - pip # Python's package-management system
  - python-graphviz # used only in chapter 6 for dot files
  - scikit-learn=0.24 # machine learning library
  - wheel # built-package format for pip
  - widgetsnbextension=3.5 # interactive HTML widgets for Jupyter notebooks
  - pip:
    - tensorboard-plugin-profile==2.4.0 # profiling plugin for TensorBoard
    - tensorboard==2.4.1 # TensorFlow's visualization toolkit
    - tensorflow-addons==0.12.1 # used only in chapter 16 for a seq2seq impl.
    - tensorflow-datasets==3.0.0 # datasets repository, ready to use
    - tensorflow-hub==0.9.0 # trained ML models repository, ready to use
    - tensorflow-probability==0.12.1 # Optional. Probability/Stats lib.
    - tensorflow-serving-api==2.4.1 # or tensorflow-serving-api-gpu if gpu
    - tensorflow==2.4.1 # Deep Learning library
    - tf-agents==0.7.1 # Reinforcement Learning lib based on TensorFlow
    - tfx==0.27.0 # platform to deploy production ML pipelines
